name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        run: npm install
      - name: Run integration tests ===>>
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm test
      - name: Generate Allure HTML report ===>>
        if: always()
        run: |
          npm run generateHtmlReport

