name: CI
on: push
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        uses: actions/setup-node@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install
      - name: Install dependencies
        run: npm install
      - name: Run integration tests ===>>
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm test
